
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znsjwpxngsbxunduadsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpuc2p3cHhuZ3NieHVuZHVhZHN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1ODExOTIsImV4cCI6MjA1ODE1NzE5Mn0.xSET8LBr6AZagcru_H_IP0IAiiCEkLk3MBshJb9ee9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
